# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Diego Castronuovo
title: Independent Software Engineer
subtitle: Mysub
description: I help startups and corporates to get ideas into production
og:description: I help startups and corporates to get ideas into production
og:title: Diego Castronuovo - I help startups and corporates to get ideas into production
email: info@diegocastronuovo.com
#website: www.diegocastronuovo.com

#seo
url: https://www.diegocastronuovo.com/
twitter:
  username: diegocastronew
  card: summary
logo:  images/profile.jpg
image:
  path:  images/profile.jpg
  height: 100
  width: 100
defaults:
  - scope:
      path: ""
    values:
      image: /images/profile.jpg

# Social links
twitter_username: diegocastronew
github_username:  castronu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: castronuovodiego
linkedin_username: castronuovodiego
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Diego and I'm a <mark>DevOps</mark> and <mark>Full-Stack</mark> engineer.
  I help startups and corporates to get ideas into production by using cutting-edge technologies like <mark>Kubernetes</mark>, <mark>OpenShift</mark>, <mark>AWS</mark> and <mark>Spring Boot</mark>.

  I started as a back-end developer in the  <mark>financial</mark> industry, where I learned  <mark>agile</mark> methods and software quality standards. Then my entrepreneurial spirit led me to work on different projects using the [lean startup](https://en.wikipedia.org/wiki/Lean_startup){:target='_blank'} method.

  Some principles I use: [Twelve Factor App Methodology](https://en.wikipedia.org/wiki/Twelve-Factor_App_methodology){:target='_blank'}, [Unix Philosophy](https://en.wikipedia.org/wiki/Unix_philosophy){:target='_blank'}, and [The Agile Manifesto](https://en.wikipedia.org/wiki/Agile_software_development#The_Agile_Manifesto){:target='_blank'}.

  I'm always open to discuss ideas and collaboration opportunities.



# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Being a father
   - Cooking
   - Travelling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jekyll-redirect-from
