# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Diego Castronuovo
title: Independent DevOps Architect
subtitle: Mysub
description: DevOps and Full-Stack engineer available remotely. I help startups and corporates to get ideas into production.
og:description: DevOps and Full-Stack engineer available remotely. I help startups and corporates to get ideas into production.
og:title: Diego Castronuovo - I help startups and corporates to get ideas into production
email: info@diegocastronuovo.com
#website: www.diegocastronuovo.com

#seo
url: https://www.diegocastronuovo.com/
twitter:
  username: diegocastronew
  card: summary
logo:  images/profile.jpg
image:
  path:  images/profile.jpg
  height: 100
  width: 100
defaults:
  - scope:
      path: ""
    values:
      image: /images/profile.jpg

# Social links
twitter_username: diegocastronew
github_username:  castronu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: castronuovodiego
linkedin_username: castronuovodiego
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs

  Greetings, I am Diego, a skilled DevOps and Full-Stack Engineer with expertise in helping businesses ranging from startups to corporates to deploy their ideas into production. My proficiency lies in utilizing advanced technologies such as Kubernetes, AWS services and GitOps to optimize the development, delivery, and deployment processes.

  My professional journey began as a back-end developer in the financial industry, where I gained knowledge of agile methodologies and software quality standards. I have since honed my skills, incorporating principles of the lean startup method into my work across diverse projects.

  My unwavering commitment to collaboration and sharing knowledge make me an approachable team player. I am always eager to connect with individuals and businesses to explore ideas and discuss opportunities for collaboration.


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Being a father
   - Cooking
   - Travelling
# Footer
footer_show_references: true

# Build settings
remote_theme: castronu/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
